### ISSUE TITLE
Webcamoid is indexing ALL the files in the systems.

### ISSUE THREAD

**Issue by Phuxxi** [webcamoid/webcamoid.github.io#2]
Hi all this is a simple problem that involves several parties.

First off Christian Boxdoerfer makes a truly exceptional search program for Linux called Fsearch.

Ryo Nakano Reco - Record talks to remember the contents later

https://github.com/ryonakano/reco

Take photos and record videos with your webcam

https://webcamoid.github.io/

The problem I am now facing is that when I do a search for files - mp3's, pictures, videos, documents etc., using Fsearch, these programs that have NOTHING to do with any thing, have backed up a file NAME list - of everything on my hard drives... like 1.5 million files.

And Fsearch cannot be faulted, but after much looking I can't see any overt ways to cut specific directories from the search.

You see there are legitimate file name pathways, e.g. Home/Desktop/Elvis Movies/ etc. And then there are these files...

Mostly these two: And there are copies of EVERY file NAME on the system....

/run/user/1000/doc/by-app/com.github.ryonakano.reco/ etc.

/run/user/1000/doc/by-app/io.github.webcamoid.Webcamoid/ etc.

So the programs have coding defects.

Can the people responsible for the apparently copied or replicated coding error please clean them up.

And Christian - if you could include a way to permanently lock out some pathways when doing a search.

Thanks to all.

Shane T. Hanson

![Idi Amin](https://github.com/webcamoid/webcamoid.github.io/assets/72900099/11965956-48c2-46b0-b842-67ab11fe542b)

![github-webcamoid](https://github.com/webcamoid/webcamoid.github.io/assets/72900099/b12d2401-b375-482d-9243-bc6d899aea65)

![github-ryonakano](https://github.com/webcamoid/webcamoid.github.io/assets/72900099/2e625344-2aa2-4a15-bf0c-7087e3e3e0fb)

**Comment by hipersayanX** [comment]
Support is only for sponsors, also this is not the place for reporting issues.
